
import java.text.SimpleDateFormat;
import java.util.Date;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author charm
 */
public class AdminLogIn_Frame extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogIn_Frame
     */
    
    DBHelper dbh = new DBHelper();
    
    public AdminLogIn_Frame() {
        initComponents();   
        showDate();
        showTime();
    }
    
    
    void showDate(){     
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
        Datelbl.setText(Datelbl.getText()+sdf.format(d));
    }
    
    void showTime(){
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        Timelbl.setText(Timelbl.getText()+sdf.format(d));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Admin_UserNamelbl = new javax.swing.JLabel();
        Admin_Usernametxt = new javax.swing.JTextField();
        Admin_Passwordfield = new javax.swing.JPasswordField();
        Admin_Passwordlbl = new javax.swing.JLabel();
        Admin_LogInButton = new javax.swing.JButton();
        UserSwitchButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Admin_CancelButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Datelbl = new javax.swing.JLabel();
        Timelbl = new javax.swing.JLabel();
        Admin_UserNamelbl1 = new javax.swing.JLabel();
        Admin_IDNumbertxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AdminRegistrationButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Log-In");
        setPreferredSize(new java.awt.Dimension(560, 457));

        jPanel1.setBackground(new java.awt.Color(243, 229, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(546, 492));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel1.setText("Senior Citizen Financial Aid Distribribution Application");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Admin Log-In");

        Admin_UserNamelbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Admin_UserNamelbl.setText("Username");
        Admin_UserNamelbl.setName("Admin_UserNamelbl"); // NOI18N

        Admin_Usernametxt.setName("Admin_Usernametxt"); // NOI18N

        Admin_Passwordfield.setName("Admin_Passwordfield"); // NOI18N
        Admin_Passwordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_PasswordfieldActionPerformed(evt);
            }
        });

        Admin_Passwordlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Admin_Passwordlbl.setText("Password");
        Admin_Passwordlbl.setName("Admin_Passwordlbl"); // NOI18N

        Admin_LogInButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Admin_LogInButton.setText("Log-in");
        Admin_LogInButton.setName("Admin_LogInButton"); // NOI18N
        Admin_LogInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_LogInButtonActionPerformed(evt);
            }
        });

        UserSwitchButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UserSwitchButton.setText("Click here");
        UserSwitchButton.setName("UserSwitchButton"); // NOI18N
        UserSwitchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserSwitchButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Not an admin?");

        Admin_CancelButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Admin_CancelButton.setText("Cancel");
        Admin_CancelButton.setName("Admin_CancelButton"); // NOI18N
        Admin_CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_CancelButtonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jLabel12.setText("Charmaine Mae I. Ramirez - BSIT-2-G1");

        Datelbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Datelbl.setText("Date: ");
        Datelbl.setName("Datelbl"); // NOI18N

        Timelbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Timelbl.setText("Time: ");
        Timelbl.setName("Timelbl"); // NOI18N

        Admin_UserNamelbl1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Admin_UserNamelbl1.setText("ID Number");
        Admin_UserNamelbl1.setName("Admin_UserNamelbl"); // NOI18N

        Admin_IDNumbertxt.setName("Admin_Usernametxt"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("No account yet?");

        AdminRegistrationButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AdminRegistrationButton.setText("Click here");
        AdminRegistrationButton.setName("AdminRegistrationButton"); // NOI18N
        AdminRegistrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminRegistrationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addGap(109, 109, 109)
                        .addComponent(Datelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Timelbl, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(82, 82, 82)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Admin_UserNamelbl)
                                            .addComponent(Admin_Passwordlbl)
                                            .addComponent(Admin_UserNamelbl1))
                                        .addGap(52, 52, 52)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Admin_Passwordfield)
                                            .addComponent(Admin_Usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Admin_IDNumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(Admin_LogInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(Admin_CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(UserSwitchButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AdminRegistrationButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Datelbl)
                        .addComponent(Timelbl))
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admin_UserNamelbl1)
                    .addComponent(Admin_IDNumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admin_Usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Admin_UserNamelbl))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admin_Passwordfield, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Admin_Passwordlbl))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Admin_LogInButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Admin_CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(AdminRegistrationButton))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(UserSwitchButton)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        Admin_UserNamelbl.getAccessibleContext().setAccessibleName("Admin_UserNamelbl");
        Admin_Usernametxt.getAccessibleContext().setAccessibleName("Admin_Usernametxt");
        Admin_Passwordfield.getAccessibleContext().setAccessibleName("Admin_Passwordfield");
        Admin_Passwordlbl.getAccessibleContext().setAccessibleName("Admin_Passwordlbl");
        Admin_LogInButton.getAccessibleContext().setAccessibleName("Admin_LogInButton");
        UserSwitchButton.getAccessibleContext().setAccessibleName("UserSwitchButton");
        Admin_CancelButton.getAccessibleContext().setAccessibleName("Admin_CancelButton");
        AdminRegistrationButton.getAccessibleContext().setAccessibleName("AdminRegistrationButton");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Admin_PasswordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_PasswordfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Admin_PasswordfieldActionPerformed

    private void UserSwitchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserSwitchButtonActionPerformed
        // TODO add your handling code here:
        new UserLogIn_Frame().setVisible(true);
    }//GEN-LAST:event_UserSwitchButtonActionPerformed

    private void Admin_CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_CancelButtonActionPerformed
        // TODO add your handling code here:
        Admin_IDNumbertxt.setText("");
        Admin_Usernametxt.setText("");
        Admin_Passwordfield.setText("");
    }//GEN-LAST:event_Admin_CancelButtonActionPerformed

    private void Admin_LogInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_LogInButtonActionPerformed
        // TODO add your handling code here:
        new AdminDashboard_Frame().setVisible(true);
    }//GEN-LAST:event_Admin_LogInButtonActionPerformed

    private void AdminRegistrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminRegistrationButtonActionPerformed
        // TODO add your handling code here:
        new AdminRegistration_Frame().setVisible(true);
    }//GEN-LAST:event_AdminRegistrationButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogIn_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminRegistrationButton;
    private javax.swing.JButton Admin_CancelButton;
    private javax.swing.JTextField Admin_IDNumbertxt;
    private javax.swing.JButton Admin_LogInButton;
    private javax.swing.JPasswordField Admin_Passwordfield;
    private javax.swing.JLabel Admin_Passwordlbl;
    private javax.swing.JLabel Admin_UserNamelbl;
    private javax.swing.JLabel Admin_UserNamelbl1;
    private javax.swing.JTextField Admin_Usernametxt;
    private javax.swing.JLabel Datelbl;
    private javax.swing.JLabel Timelbl;
    private javax.swing.JButton UserSwitchButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
