/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author charm
 */

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class AdminDashboard_Frame extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard_Frame
     */
    
    DBHelper dbh = new DBHelper();
    
    public AdminDashboard_Frame() {
        initComponents();
        try {
            dbh.ConnectDB();
        }catch (Exception ex) {
            Logger.getLogger(UserRegistration_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        showDate();
        showTime();
    }
    
    
    void showDate(){     
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
        Datelbl.setText(Datelbl.getText()+sdf.format(d));
    }
    
    void showTime(){
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        Timelbl.setText(Timelbl.getText()+sdf.format(d));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ModifyORDeleteDataButton = new javax.swing.JButton();
        SearchDataButton = new javax.swing.JButton();
        SeniorIDNumFiltertxt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        DisplayAllBirthdaysTable = new javax.swing.JTable();
        displayBirthdayButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        AddToListtxt = new javax.swing.JTextField();
        AddToListButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Listtxt = new javax.swing.JTextArea();
        Datelbl = new javax.swing.JLabel();
        Timelbl = new javax.swing.JLabel();
        AdminLogOutButton = new javax.swing.JButton();
        DisplayAllButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DisplayAllRecordsbySeniorCitizenIDNumTable = new javax.swing.JTable();
        SearchDataButton1 = new javax.swing.JButton();
        ScheduleButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(243, 229, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setText("Admin Dashboard");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Senior Citizen Financial Aid Distribribution Application");

        ModifyORDeleteDataButton.setBackground(new java.awt.Color(153, 255, 153));
        ModifyORDeleteDataButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ModifyORDeleteDataButton.setText("Modify or Delete Records in the Database");
        ModifyORDeleteDataButton.setToolTipText("");
        ModifyORDeleteDataButton.setName("ModifyORDeleteDataButton"); // NOI18N
        ModifyORDeleteDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyORDeleteDataButtonActionPerformed(evt);
            }
        });

        SearchDataButton.setBackground(new java.awt.Color(255, 255, 153));
        SearchDataButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SearchDataButton.setText("Search");
        SearchDataButton.setName("SearchDataButton"); // NOI18N
        SearchDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchDataButtonActionPerformed(evt);
            }
        });

        SeniorIDNumFiltertxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SeniorIDNumFiltertxt.setText("Enter Senior Citizen ID Number");
        SeniorIDNumFiltertxt.setName("SeniorIDNumFiltertxt"); // NOI18N
        SeniorIDNumFiltertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeniorIDNumFiltertxtActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 200));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Upcoming Birthdays");

        DisplayAllBirthdaysTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Senior Citizen ID #", "Month", "Day", "Year"
            }
        ));
        jScrollPane4.setViewportView(DisplayAllBirthdaysTable);

        displayBirthdayButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        displayBirthdayButton.setText("DISPLAY");
        displayBirthdayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBirthdayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(displayBirthdayButton)
                        .addGap(170, 170, 170))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayBirthdayButton)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 200));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Important Events");

        AddToListtxt.setName("AddToListtxt"); // NOI18N
        AddToListtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToListtxtActionPerformed(evt);
            }
        });

        AddToListButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddToListButton.setText("Add to List");
        AddToListButton.setName("AddToListButton"); // NOI18N
        AddToListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToListButtonActionPerformed(evt);
            }
        });

        Listtxt.setEditable(false);
        Listtxt.setBackground(new java.awt.Color(255, 255, 255));
        Listtxt.setColumns(20);
        Listtxt.setRows(5);
        Listtxt.setText("Submit final list");
        Listtxt.setName("Listtxt"); // NOI18N
        jScrollPane1.setViewportView(Listtxt);
        Listtxt.getAccessibleContext().setAccessibleName("Listtxt");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(AddToListtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AddToListButton)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddToListtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddToListButton))
                .addGap(20, 20, 20))
        );

        AddToListtxt.getAccessibleContext().setAccessibleName("AddToListtxt");
        AddToListButton.getAccessibleContext().setAccessibleName("AddToListButton");

        Datelbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Datelbl.setText("Date: ");
        Datelbl.setName("Datelbl"); // NOI18N

        Timelbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Timelbl.setText("Time: ");
        Timelbl.setName("Timelbl"); // NOI18N

        AdminLogOutButton.setBackground(new java.awt.Color(102, 204, 255));
        AdminLogOutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AdminLogOutButton.setText("Log-out");
        AdminLogOutButton.setName("AdminLogOutButton"); // NOI18N
        AdminLogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLogOutButtonActionPerformed(evt);
            }
        });

        DisplayAllButton.setBackground(new java.awt.Color(0, 204, 204));
        DisplayAllButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DisplayAllButton.setText("Display All Records in the Database");
        DisplayAllButton.setName("DisplayAllButton"); // NOI18N
        DisplayAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayAllButtonActionPerformed(evt);
            }
        });

        DisplayAllRecordsbySeniorCitizenIDNumTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Senior Citizen ID Number", "Voter's ID Number", "First Name", "Middle Name", "Last Name", "Gender", "Vaccination Status", "Birth Day", "Birth Month", "Birth Year", "House Number", "Street", "Baranggay", "City", "Province", "Zip Code", "Contact Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DisplayAllRecordsbySeniorCitizenIDNumTable.setName("DisplayAllRecordsbySeniorCitizenIDNumTable"); // NOI18N
        jScrollPane2.setViewportView(DisplayAllRecordsbySeniorCitizenIDNumTable);

        SearchDataButton1.setBackground(new java.awt.Color(255, 255, 153));
        SearchDataButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SearchDataButton1.setText("Clear");
        SearchDataButton1.setToolTipText("");
        SearchDataButton1.setName("SearchDataButton"); // NOI18N
        SearchDataButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchDataButton1ActionPerformed(evt);
            }
        });

        ScheduleButton.setBackground(new java.awt.Color(255, 255, 51));
        ScheduleButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ScheduleButton.setText("Schedule an Event for a User");
        ScheduleButton.setName("ScheduleButton"); // NOI18N
        ScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScheduleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(666, 666, 666)
                        .addComponent(Datelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Timelbl, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ModifyORDeleteDataButton)
                        .addGap(24, 24, 24)
                        .addComponent(DisplayAllButton)
                        .addGap(18, 18, 18)
                        .addComponent(ScheduleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AdminLogOutButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(SeniorIDNumFiltertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SearchDataButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchDataButton1)
                        .addGap(316, 316, 316))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(480, 480, 480))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Datelbl)
                    .addComponent(Timelbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SeniorIDNumFiltertxt)
                    .addComponent(SearchDataButton)
                    .addComponent(SearchDataButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ModifyORDeleteDataButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AdminLogOutButton)
                        .addComponent(ScheduleButton)
                        .addComponent(DisplayAllButton)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        ModifyORDeleteDataButton.getAccessibleContext().setAccessibleName("ModifyDataButton");
        SearchDataButton.getAccessibleContext().setAccessibleName("SearchDataButton");
        SeniorIDNumFiltertxt.getAccessibleContext().setAccessibleName("Nametxt");
        Datelbl.getAccessibleContext().setAccessibleName("Datelbl");
        Timelbl.getAccessibleContext().setAccessibleName("Timelbl");
        AdminLogOutButton.getAccessibleContext().setAccessibleName("AdminLogOutButton");
        DisplayAllButton.getAccessibleContext().setAccessibleName("DisplayAllButton");
        ScheduleButton.getAccessibleContext().setAccessibleName("ScheduleButton");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeniorIDNumFiltertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeniorIDNumFiltertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeniorIDNumFiltertxtActionPerformed

    private void AddToListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToListButtonActionPerformed
        // TODO add your handling code here:
        Listtxt.append("\n"+AddToListtxt.getText());
        AddToListtxt.setText("");
   
    }//GEN-LAST:event_AddToListButtonActionPerformed

    private void AddToListtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToListtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddToListtxtActionPerformed

    private void ModifyORDeleteDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyORDeleteDataButtonActionPerformed
        // TODO add your handling code here:
        new DisplayARecordFromUserInformationForModifyOrDelete_Frame().setVisible(true);
    }//GEN-LAST:event_ModifyORDeleteDataButtonActionPerformed

    private void AdminLogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLogOutButtonActionPerformed
        // TODO add your handling code here:
        new AdminLogIn_Frame().setVisible(true);
    }//GEN-LAST:event_AdminLogOutButtonActionPerformed

    private void DisplayAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayAllButtonActionPerformed
        // TODO add your handling code here:
        new DisplayAllUserInformationRecords_Frame().setVisible(true);
    }//GEN-LAST:event_DisplayAllButtonActionPerformed

    private void SearchDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchDataButtonActionPerformed
        // TODO add your handling code here:
        int seniorIDNum = Integer.parseInt(SeniorIDNumFiltertxt.getText());
        ResultSet rs = dbh.displayBySeniorCitizenIDNum(seniorIDNum);
 
        try {
            while (DisplayAllRecordsbySeniorCitizenIDNumTable.getRowCount()>0){
                ((DefaultTableModel) DisplayAllRecordsbySeniorCitizenIDNumTable.getModel()).removeRow(0);
            }
             int columns = rs.getMetaData().getColumnCount();
            while(rs.next()){
                Object [] row = new Object [columns];
                    for(int i=1; i<=columns; i++){
                        row[i-1] = rs.getObject(i);
                    }
                ((DefaultTableModel) DisplayAllRecordsbySeniorCitizenIDNumTable.getModel()).insertRow(rs.getRow()-1, row);
            }
        }catch (SQLException ex) {
            Logger.getLogger(DisplayAllUserInformationRecords_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SearchDataButtonActionPerformed

    private void displayBirthdayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBirthdayButtonActionPerformed
        // TODO add your handling code here:
        
        ResultSet rs = dbh.displayByBirthday();
        
        try {
            while (DisplayAllBirthdaysTable.getRowCount()>0){
                ((DefaultTableModel) DisplayAllBirthdaysTable.getModel()).removeRow(0);
            }
             int columns = rs.getMetaData().getColumnCount();
            while(rs.next()){
                Object [] row = new Object [columns];
                    for(int i=1; i<=columns; i++){
                        row[i-1] = rs.getObject(i);
                    }
                ((DefaultTableModel) DisplayAllBirthdaysTable.getModel()).insertRow(rs.getRow()-1, row);
            }
        }catch (SQLException ex) {
            Logger.getLogger(DisplayAllUserInformationRecords_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_displayBirthdayButtonActionPerformed

    private void SearchDataButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchDataButton1ActionPerformed
        // TODO add your handling code here:
        SeniorIDNumFiltertxt.setText("");
    }//GEN-LAST:event_SearchDataButton1ActionPerformed

    private void ScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScheduleButtonActionPerformed
        // TODO add your handling code here:
        new ScheduleSetterForAdmins_Frame().setVisible(true);
    }//GEN-LAST:event_ScheduleButtonActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToListButton;
    private javax.swing.JTextField AddToListtxt;
    private javax.swing.JButton AdminLogOutButton;
    private javax.swing.JLabel Datelbl;
    private javax.swing.JTable DisplayAllBirthdaysTable;
    private javax.swing.JButton DisplayAllButton;
    private javax.swing.JTable DisplayAllRecordsbySeniorCitizenIDNumTable;
    private javax.swing.JTextArea Listtxt;
    private javax.swing.JButton ModifyORDeleteDataButton;
    private javax.swing.JButton ScheduleButton;
    private javax.swing.JButton SearchDataButton;
    private javax.swing.JButton SearchDataButton1;
    private javax.swing.JTextField SeniorIDNumFiltertxt;
    private javax.swing.JLabel Timelbl;
    private javax.swing.JButton displayBirthdayButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private String toString(Date d) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
