
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author charm
 */
public class DisplayARecordFromUserInformationForModifyOrDelete_Frame extends javax.swing.JFrame {

    /**
     * Creates new form DisplayARecordFromUserInformationForModifyOrDelete_Frame
     */
    
    DBHelper dbh = new DBHelper();
    
    public DisplayARecordFromUserInformationForModifyOrDelete_Frame() {
        initComponents();
         try {
            dbh.ConnectDB();
        }catch (Exception ex) {
            Logger.getLogger(UserRegistration_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        showDate();
        showTime();
    }
    
    void showDate(){     
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
        Datelbl.setText(Datelbl.getText()+sdf.format(d));
    }
    
    void showTime(){
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        Timelbl.setText(Timelbl.getText()+sdf.format(d));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        FirstNametxtfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        MiddleNametxtfield = new javax.swing.JTextField();
        LastNametxtfield = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        VotersIDtxtfield = new javax.swing.JTextField();
        VaxStatustxtfield = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        BirthMonthtxtfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        BirthDaytxtfield = new javax.swing.JTextField();
        BirthYeartxtfield = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Gendertxtfield = new javax.swing.JTextField();
        ContactNumbertxtfield = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        HomeNumtxtfield = new javax.swing.JTextField();
        StreetNametxtfield = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Baranggaytxtfield = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Citytxtfield = new javax.swing.JTextField();
        Provincetxtfield = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ZipCodetxtfield = new javax.swing.JTextField();
        SeniorIDNumFiltertxt = new javax.swing.JTextField();
        SearchRecordButton = new javax.swing.JButton();
        ModifyRecordButton = new javax.swing.JButton();
        DeleteRecordButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Datelbl = new javax.swing.JLabel();
        Timelbl = new javax.swing.JLabel();
        ClearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 229, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Enter Senior Citizen ID #");

        FirstNametxtfield.setName("FirstNametxtfield"); // NOI18N
        FirstNametxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNametxtfieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("First Name");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Middle Name");

        MiddleNametxtfield.setName("MiddleNametxtfield"); // NOI18N

        LastNametxtfield.setName("LastNametxtfield"); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Last Name");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Voter's ID #");

        VotersIDtxtfield.setName("VotersIDtxtfield"); // NOI18N

        VaxStatustxtfield.setName("VaxStatustxtfield"); // NOI18N
        VaxStatustxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VaxStatustxtfieldActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Vaccination Staus");

        BirthMonthtxtfield.setName("BirthMonthtxtfield"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Birth Month");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Birth Day");

        BirthDaytxtfield.setName("BirthDaytxtfield"); // NOI18N
        BirthDaytxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthDaytxtfieldActionPerformed(evt);
            }
        });

        BirthYeartxtfield.setName("BirthYeartxtfield"); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Birth Year");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Enter Gender");

        Gendertxtfield.setName("Gendertxtfield"); // NOI18N

        ContactNumbertxtfield.setName("ContactNumbertxtfield"); // NOI18N
        ContactNumbertxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactNumbertxtfieldActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Contact Number");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Home Number");

        HomeNumtxtfield.setName("HomeNumtxtfield"); // NOI18N

        StreetNametxtfield.setName("StreetNametxtfield"); // NOI18N
        StreetNametxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StreetNametxtfieldActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Street Name");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Baranggay");

        Baranggaytxtfield.setName("Baranggaytxtfield"); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("City");

        Citytxtfield.setName("Citytxtfield"); // NOI18N
        Citytxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CitytxtfieldActionPerformed(evt);
            }
        });

        Provincetxtfield.setName("Provincetxtfield"); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Province");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Zip Code");

        ZipCodetxtfield.setName("ZipCodetxtfield"); // NOI18N

        SeniorIDNumFiltertxt.setName("SeniorIDNumFiltertxt"); // NOI18N
        SeniorIDNumFiltertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeniorIDNumFiltertxtActionPerformed(evt);
            }
        });

        SearchRecordButton.setBackground(new java.awt.Color(255, 255, 153));
        SearchRecordButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SearchRecordButton.setText("Search Record");
        SearchRecordButton.setName("SearchRecordButton"); // NOI18N
        SearchRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchRecordButtonActionPerformed(evt);
            }
        });

        ModifyRecordButton.setBackground(new java.awt.Color(102, 153, 255));
        ModifyRecordButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ModifyRecordButton.setText("Modify Record");
        ModifyRecordButton.setName("ModifyRecordButton"); // NOI18N
        ModifyRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyRecordButtonActionPerformed(evt);
            }
        });

        DeleteRecordButton.setBackground(new java.awt.Color(255, 102, 102));
        DeleteRecordButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DeleteRecordButton.setText("Delete Record");
        DeleteRecordButton.setName("DeleteRecordButton"); // NOI18N
        DeleteRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRecordButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Senior Citizen Financial Aid Distribribution Application");

        Datelbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Datelbl.setText("Date: ");
        Datelbl.setName("Datelbl"); // NOI18N

        Timelbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Timelbl.setText("Time: ");
        Timelbl.setName("Timelbl"); // NOI18N

        ClearButton.setBackground(new java.awt.Color(255, 255, 153));
        ClearButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.setName("ClearButton"); // NOI18N
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FirstNametxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VotersIDtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MiddleNametxtfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastNametxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VaxStatustxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ContactNumbertxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Gendertxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BirthYeartxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BirthDaytxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(51, 51, 51)
                        .addComponent(BirthMonthtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel23))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(StreetNametxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HomeNumtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Datelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Timelbl, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel18))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ZipCodetxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Citytxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addGap(55, 55, 55)
                                    .addComponent(Baranggaytxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Provincetxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addComponent(ModifyRecordButton)
                        .addGap(71, 71, 71)
                        .addComponent(DeleteRecordButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(433, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(SeniorIDNumFiltertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SearchRecordButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Datelbl)
                        .addComponent(Timelbl))
                    .addComponent(jLabel2))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(SeniorIDNumFiltertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchRecordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(FirstNametxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(MiddleNametxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(LastNametxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VotersIDtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(VaxStatustxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(BirthMonthtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(HomeNumtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(BirthDaytxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(StreetNametxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(BirthYeartxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(Baranggaytxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Gendertxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel17)
                            .addComponent(Citytxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(ContactNumbertxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(Provincetxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(ZipCodetxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModifyRecordButton)
                    .addComponent(DeleteRecordButton))
                .addGap(42, 42, 42))
        );

        SearchRecordButton.getAccessibleContext().setAccessibleName("SearchRecordButton");
        ModifyRecordButton.getAccessibleContext().setAccessibleName("ModifyRecordButton");
        DeleteRecordButton.getAccessibleContext().setAccessibleName("DeleteRecordButton");
        ClearButton.getAccessibleContext().setAccessibleName("ClearButton");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FirstNametxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNametxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNametxtfieldActionPerformed

    private void BirthDaytxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthDaytxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthDaytxtfieldActionPerformed

    private void StreetNametxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StreetNametxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StreetNametxtfieldActionPerformed

    private void ContactNumbertxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactNumbertxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactNumbertxtfieldActionPerformed

    private void CitytxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CitytxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CitytxtfieldActionPerformed

    private void VaxStatustxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VaxStatustxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VaxStatustxtfieldActionPerformed

    private void SeniorIDNumFiltertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeniorIDNumFiltertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeniorIDNumFiltertxtActionPerformed

    private void SearchRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchRecordButtonActionPerformed
        // TODO add your handling code here:
        int seniorIDNum = Integer.parseInt(SeniorIDNumFiltertxt.getText());
        ResultSet rs = dbh.displayBySeniorCitizenIDNum(seniorIDNum);

        try {
            while(rs.next()){
                VotersIDtxtfield.setText(rs.getString(2));
                FirstNametxtfield.setText(rs.getString(3));
                MiddleNametxtfield.setText(rs.getString(4));
                LastNametxtfield.setText(rs.getString(5));
                Gendertxtfield.setText(rs.getString(6));
                VaxStatustxtfield.setText(rs.getString(7));
                BirthDaytxtfield.setText(rs.getString(8));
                BirthMonthtxtfield.setText(rs.getString(9)); 
                BirthYeartxtfield.setText(rs.getString(10));            
                HomeNumtxtfield.setText(rs.getString(11));
                StreetNametxtfield.setText(rs.getString(12));
                Baranggaytxtfield.setText(rs.getString(13));
                Citytxtfield.setText(rs.getString(14));
                Provincetxtfield.setText(rs.getString(15));
                ZipCodetxtfield.setText(rs.getString(16));
                ContactNumbertxtfield.setText(rs.getString(17));
            }
            
                
        }catch (SQLException ex) {
            Logger.getLogger(DisplayAllUserInformationRecords_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SearchRecordButtonActionPerformed

    private void ModifyRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyRecordButtonActionPerformed
        // TODO add your handling code here:
        int seniorIDNum = Integer.parseInt(SeniorIDNumFiltertxt.getText());
        String votersIDNum = VotersIDtxtfield.getText();
        String fName = FirstNametxtfield.getText();
        String mName = MiddleNametxtfield.getText();
        String lName = LastNametxtfield.getText();
        String gender = Gendertxtfield.getText();
        boolean vaxStatus = Boolean.parseBoolean(VaxStatustxtfield.getText());
        int birthDay = Integer.parseInt(BirthDaytxtfield.getText());
        String birthMonth = BirthMonthtxtfield.getText();
        int birthYear = Integer.parseInt(BirthYeartxtfield.getText());
        int houseNum = Integer.parseInt(HomeNumtxtfield.getText());
        String street = StreetNametxtfield.getText();
        String baranggay = Baranggaytxtfield.getText();
        String city = Citytxtfield.getText();
        String prov = Provincetxtfield.getText();
        int zipCode = Integer.parseInt(ZipCodetxtfield.getText());
        String contactNum = ContactNumbertxtfield.getText();
        
        boolean upd = dbh.UpdateRecord(seniorIDNum, votersIDNum, fName, mName, lName, gender, vaxStatus, birthDay, birthMonth, birthYear, houseNum, street, baranggay, city, prov, zipCode, contactNum);
       if(upd)
            System.out.println("Record Updated.");
        else
            System.out.println("Record Not Updated.");    
        
        
    }//GEN-LAST:event_ModifyRecordButtonActionPerformed

    private void DeleteRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRecordButtonActionPerformed
        // TODO add your handling code here:
        int seniorIDNum = Integer.parseInt(SeniorIDNumFiltertxt.getText());
        
        int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this record?", "Delete Record", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(result == JOptionPane.YES_OPTION){
            boolean delInfo = dbh.deleteUserInformationRecord(seniorIDNum);
            boolean delCredentials = dbh.deleteUserCredentialsRecord(seniorIDNum);
            boolean delUserSched = dbh.deleteUserScheduleRecord(seniorIDNum);
            if(delInfo && delCredentials)
               JOptionPane.showMessageDialog(this, "Record Deleted");
            else
                JOptionPane.showMessageDialog(this, "Record Not Deleted");
            
        }
    }//GEN-LAST:event_DeleteRecordButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
        SeniorIDNumFiltertxt.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayARecordFromUserInformationForModifyOrDelete_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayARecordFromUserInformationForModifyOrDelete_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayARecordFromUserInformationForModifyOrDelete_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayARecordFromUserInformationForModifyOrDelete_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayARecordFromUserInformationForModifyOrDelete_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Baranggaytxtfield;
    private javax.swing.JTextField BirthDaytxtfield;
    private javax.swing.JTextField BirthMonthtxtfield;
    private javax.swing.JTextField BirthYeartxtfield;
    private javax.swing.JTextField Citytxtfield;
    private javax.swing.JButton ClearButton;
    private javax.swing.JTextField ContactNumbertxtfield;
    private javax.swing.JLabel Datelbl;
    private javax.swing.JButton DeleteRecordButton;
    private javax.swing.JTextField FirstNametxtfield;
    private javax.swing.JTextField Gendertxtfield;
    private javax.swing.JTextField HomeNumtxtfield;
    private javax.swing.JTextField LastNametxtfield;
    private javax.swing.JTextField MiddleNametxtfield;
    private javax.swing.JButton ModifyRecordButton;
    private javax.swing.JTextField Provincetxtfield;
    private javax.swing.JButton SearchRecordButton;
    private javax.swing.JTextField SeniorIDNumFiltertxt;
    private javax.swing.JTextField StreetNametxtfield;
    private javax.swing.JLabel Timelbl;
    private javax.swing.JTextField VaxStatustxtfield;
    private javax.swing.JTextField VotersIDtxtfield;
    private javax.swing.JTextField ZipCodetxtfield;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
