
import java.text.SimpleDateFormat;
import java.util.Date;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author charm
 */
public class UserLogIn_Frame extends javax.swing.JFrame {

    /**
     * Creates new form LogIn_Frame
     */
    
    DBHelper dbh = new DBHelper();
    
    public UserLogIn_Frame() {
        initComponents();
        showDate();
        showTime();
    }
    
    
    void showDate(){     
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
        Datelbl.setText(Datelbl.getText()+sdf.format(d));
    }
    
    void showTime(){
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        Timelbl.setText(Timelbl.getText()+sdf.format(d));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        User_UserNamelbl = new javax.swing.JLabel();
        UserSeniorCitizenIDNumtxt = new javax.swing.JTextField();
        User_Passwordlbl = new javax.swing.JLabel();
        User_LogInButton = new javax.swing.JButton();
        AdminSwitchButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RegisterButton = new javax.swing.JButton();
        User_Passwordfield = new javax.swing.JPasswordField();
        User_CancelButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Datelbl = new javax.swing.JLabel();
        Timelbl = new javax.swing.JLabel();
        User_Usernametxt = new javax.swing.JTextField();
        User_UserNamelbl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Log-In");
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 254, 226));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel1.setText("Senior Citizen Financial Aid Distribribution Application");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("User Log-In");

        User_UserNamelbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        User_UserNamelbl.setText("Senior Citizen ID #");
        User_UserNamelbl.setName("User_UserNamelbl"); // NOI18N

        UserSeniorCitizenIDNumtxt.setName("UserSeniorCitizenIDNumtxt"); // NOI18N

        User_Passwordlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        User_Passwordlbl.setText("Password");
        User_Passwordlbl.setName("User_Passwordlbl"); // NOI18N

        User_LogInButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        User_LogInButton.setText("Log-in");
        User_LogInButton.setName("User_LogInButton"); // NOI18N
        User_LogInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_LogInButtonActionPerformed(evt);
            }
        });

        AdminSwitchButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AdminSwitchButton.setText("Click here");
        AdminSwitchButton.setName("AdminSwitchButton"); // NOI18N
        AdminSwitchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminSwitchButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Not a user?");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("No account yet?");

        RegisterButton.setText("Register here");
        RegisterButton.setName("RegisterButton"); // NOI18N
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        User_Passwordfield.setName("User_Passwordfield"); // NOI18N

        User_CancelButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        User_CancelButton.setText("Cancel");
        User_CancelButton.setName("User_CancelButton"); // NOI18N
        User_CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_CancelButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jLabel2.setText("Charmaine Mae I. Ramirez - BSIT-2-G1");

        Datelbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Datelbl.setText("Date: ");
        Datelbl.setName("Datelbl"); // NOI18N

        Timelbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Timelbl.setText("Time: ");
        Timelbl.setName("Timelbl"); // NOI18N

        User_Usernametxt.setName("User_Usernametxt"); // NOI18N
        User_Usernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_UsernametxtActionPerformed(evt);
            }
        });

        User_UserNamelbl1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        User_UserNamelbl1.setText("Username");
        User_UserNamelbl1.setName("User_UserNamelbl"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(109, 109, 109)
                        .addComponent(Datelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Timelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(User_UserNamelbl)
                                    .addComponent(User_Passwordlbl)
                                    .addComponent(User_UserNamelbl1))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(UserSeniorCitizenIDNumtxt)
                                    .addComponent(User_Passwordfield, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(User_Usernametxt)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AdminSwitchButton)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RegisterButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(User_LogInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(User_CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Datelbl)
                        .addComponent(Timelbl))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserSeniorCitizenIDNumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(User_UserNamelbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(User_Usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(User_UserNamelbl1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(User_Passwordfield, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(User_Passwordlbl))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(User_LogInButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(User_CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminSwitchButton)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(RegisterButton))
                .addGap(50, 50, 50))
        );

        User_UserNamelbl.getAccessibleContext().setAccessibleName("User_UserNamelbl");
        UserSeniorCitizenIDNumtxt.getAccessibleContext().setAccessibleName("User_Usernametxt");
        User_Passwordlbl.getAccessibleContext().setAccessibleName("User_Passwordlbl");
        User_LogInButton.getAccessibleContext().setAccessibleName("User_LogInButton");
        AdminSwitchButton.getAccessibleContext().setAccessibleName("AdminSwitchButton");
        RegisterButton.getAccessibleContext().setAccessibleName("RegisterButton");
        User_Passwordfield.getAccessibleContext().setAccessibleName("User_Passwordfield");
        User_CancelButton.getAccessibleContext().setAccessibleName("User_CancelButton");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here
        new UserRegistration_Frame().setVisible(true);
       
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void User_LogInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_LogInButtonActionPerformed
        // TODO add your handling code here:
        new UserDashboard_Frame().setVisible(true);
    }//GEN-LAST:event_User_LogInButtonActionPerformed

    private void AdminSwitchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminSwitchButtonActionPerformed
        // TODO add your handling code here:
        new AdminLogIn_Frame().setVisible(true);
    }//GEN-LAST:event_AdminSwitchButtonActionPerformed

    private void User_CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_CancelButtonActionPerformed
        // TODO add your handling code here:
        UserSeniorCitizenIDNumtxt.setText("");
        User_Usernametxt.setText("");
        User_Passwordfield.setText("");
    }//GEN-LAST:event_User_CancelButtonActionPerformed

    private void User_UsernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_UsernametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_User_UsernametxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogIn_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogIn_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogIn_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogIn_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            @Override
            public void run() {
                new UserLogIn_Frame().setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminSwitchButton;
    private javax.swing.JLabel Datelbl;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel Timelbl;
    private javax.swing.JTextField UserSeniorCitizenIDNumtxt;
    private javax.swing.JButton User_CancelButton;
    private javax.swing.JButton User_LogInButton;
    private javax.swing.JPasswordField User_Passwordfield;
    private javax.swing.JLabel User_Passwordlbl;
    private javax.swing.JLabel User_UserNamelbl;
    private javax.swing.JLabel User_UserNamelbl1;
    private javax.swing.JTextField User_Usernametxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
